### ISSUE TITLE
Chapter 5 - 03_pyfolio_demo - ValueError: unsupported pickle protocol: 5 

### ISSUE THREAD

**Issue by JeremyWhittaker** [stefan-jansen/machine-learning-for-trading#131] opened 2021-03-19 23:09 UTC
data folder create_datasets uses ml4t environment to create the data files. If you attempt to run chapter 4 - 03_pyfolio_demo while in backtest environment you get an error `ValueError: unsupported pickle protocol: 5`

The issue is chapter 4 - 03_pyfolio_demo won't run in ml4t environment and data \ create_datasets won't run in the backtest environment due to dependencies. 

I fixed this by running create_datasets in the backtest environment. However, I had to add the following code for it to work.
```
!conda install -n backtest html5lib -y
!conda install -n backtest BeautifulSoup4 -y
```

I'm not sure if it's the proper fix but it appeared to work.

**Comment by sabirjana** [comment] 2021-03-20 16:57
[https://github.com/stefan-jansen/machine-learning-for-trading/issues/130](url) I too faced this issue.

**Comment by stefan-jansen** [comment] 2021-03-20 20:04
Using the environment `ml4t` to write to HDF5 and `backtest` to read (switch via Kernel menu) doesn't appear to cause problems, so not sure I can reproduce this error. When you run `import sys;sys.prefix` does it show the same Python version 3.6.13 as in the screenshot?

![Screenshot from 2021-03-20 15-01-19](https://user-images.githubusercontent.com/4275885/111884108-af5a5f80-8995-11eb-9e4e-0c110662cb1c.png)

**Comment by JeremyWhittaker** [comment] 2021-03-21 00:26
![image](https://user-images.githubusercontent.com/13750325/111889746-542e6a00-89a1-11eb-93fe-dbb622660384.png)


![image](https://user-images.githubusercontent.com/13750325/111889831-5f819580-89a1-11eb-9491-bffc674b7e9c.png)

**Comment by copypasteearth** [comment] 2021-03-25 14:33
I am getting the same error. It reads the h5 file fine buy when you try to access the information using store.get() is when it throws the error

**Comment by copypasteearth** [comment] 2021-03-25 15:23
i just put in 

import pickle
pickle.HIGHEST_PROTOCOL = 4 

into the create dataset file and it works

**Comment by stefan-jansen** [comment] 2021-04-06 01:57
Just checked and my test above was of course not very useful since it didn't contain data that would be pickled, my apologies. The good news is that I've just released an updated [Zipline version](https://github.com/stefan-jansen/zipline-reloaded) that is compatible with Python 3.7+ (see new [docs](https://zipline.ml4trading.io/) so we no longer need to switch Python versions, which in turn should eliminate this problem. 

I'll add a note into the current installation instructions to alert users of this issue with the new Docker image and will update everything next week or so to reflect the possibility to now work from a single python version / environment. 

Sorry again that I didn't catch this earlier, didn't mean to frustrate anyone here. Closing this now, feel free to reopen.

**Closed by stefan-jansen** 2021-04-06 01:57 UTC
