### ISSUE TITLE
Chapter 7 - 05-predicting stock returns with linear regression

### ISSUE THREAD

**Issue by dev-rrusso** [stefan-jansen/machine-learning-for-trading#147] opened 2021-04-15 21:45 UTC
Working through the notebook 07-05-predicting stock returns with linear regression.  Everything is fine up until running the CV with LinearRegression.  Then it just hangs forever and eventually sometimes will give the below error:

Input:
```
%%time
target = f'target_{lookahead}d'
lr_predictions, lr_scores = [], []
lr = LinearRegression()
for i, (train_idx, test_idx) in enumerate(cv.split(X), 1):
    X_train, y_train, = X.iloc[train_idx], y[target].iloc[train_idx]
    X_test, y_test = X.iloc[test_idx], y[target].iloc[test_idx]
    lr.fit(X=X_train, y=y_train)
    y_pred = lr.predict(X_test)
    
    preds = y_test.to_frame('actuals').assign(predicted=y_pred)
    preds_by_day = preds.groupby(level='date')
    scores = pd.concat([preds_by_day.apply(lambda x: spearmanr(x.predicted,
                                                               x.actuals)[0]*100)
                        .to_frame('ic'),
                        preds_by_day.apply(lambda x: np.sqrt(mean_squared_error(y_pred=x.predicted,
                                                                                y_true=x.actuals)))
                        .to_frame('rmse')], axis=1)
    lr_scores.append(scores)
    lr_predictions.append(preds)
    
lr_scores = pd.concat(lr_scores)
lr_predictions = pd.concat(lr_predictions)
```

Output (Error): 

It does nothing for about an hour, then..

Traceback (most recent call last):

  File "<timed exec>", line 8, in <module>

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\linear_model\_base.py", line 238, in predict
    return self._decision_function(X)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\linear_model\_base.py", line 220, in _decision_function
    X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\utils\validation.py", line 616, in check_array
    array = np.asarray(array, order=order, dtype=dtype)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\numpy\core\_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\pandas\core\generic.py", line 1899, in __array__
    return np.asarray(self._values, dtype=dtype)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\pandas\core\generic.py", line 5678, in _values
    return self.values

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\pandas\core\generic.py", line 5673, in values
    return self._mgr.as_array(transpose=self._AXIS_REVERSED)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\pandas\core\internals\managers.py", line 872, in as_array
    arr = self._interleave(dtype=dtype, na_value=na_value)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\pandas\core\internals\managers.py", line 901, in _interleave
    result = np.empty(self.shape, dtype=dtype)

MemoryError: Unable to allocate 17.9 MiB for an array with shape (37, 63258) and data type float64

This prevents me from being able to do the Linear Regression as well as the Ridge & Lasso.  It says a seemingly random size each time, 17.9M, 500K, 1.3G but always the same error.. Haven't been able to figure it out or get past it in a week.  

Please advise, thank you!

-Rob

**Comment by stefan-jansen** [comment] 2021-04-16 04:09
If you are using Docker, have you looked at [increasing memory](https://www.youtube.com/watch?v=dxEbtZsBO2A)?

**Comment by dev-rrusso** [comment] 2021-04-16 14:12
I'm on a Windows machine.. is it a memory issue?  Any advice to make it run?

**Comment by stefan-jansen** [comment] 2021-04-16 15:05
The error mentions this:
```
MemoryError: Unable to allocate 17.9 MiB for an array with shape (37, 63258) and data type float64
```
Since Docker Desktop sets resource usage constraints, modifying those may help. Please see the link in my previous response.

**Comment by dev-rrusso** [comment] 2021-04-16 15:18
Yes I meant to include that I’m not using Docker- I installed using conda & ml4t environment..

**Comment by stefan-jansen** [comment] 2021-04-16 19:02
I just ran this notebook in the current version of the Docker container and can't replicate this error (Docker on Windows, small laptop with 8G RAM) . Linear regression takes 20s, Ridge 4 min, Lasso 1min. 

First, I would recommend using the provided Docker image which should spare you the frustration. Unfortunately, it's rather difficult to debug alternative environment setups - hence my warning in the [installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation#how-to-install-the-required-libraries-using-conda-environments) that I can't provide much help.

Alternatively, I'm attaching a preview [ml4t-new.txt](https://github.com/stefan-jansen/machine-learning-for-trading/files/6327366/ml4t-new.txt) of a new unified environment that includes the new [Zipline version](https://zipline.ml4trading.io/) which runs on Python 3.8 as well. Please change the extension to `.yml`, GitHub only allows `.txt`. 


This is not thoroughly tested and misses Alphalens for which I still need to build a conda distro. I just ran the linear regression notebook without any issues and it's of course faster than Docker; LR in 3s, Ridge in <1min. This **should** work but I can't guarantee it and esp can't guarantee that you won't run into problems in other notebooks. The only thing tested so far is that all imports except for alphalens work. 

Hope this helps; closing for now, please feel free to reopen if you continue to run into issues even using Docker.

**Closed by stefan-jansen** 2021-04-16 19:02 UTC
