### ISSUE TITLE
chapter5: 05_strategy_evaluation: 03_pyfolio_demo.ipynb

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#153] opened 2021-04-29 18:21 UTC
**Describe the bug**
I am using the backtest env for generating assets.h5 and also for running the above project. I am getting the below error.

**To Reproduce**
- as above

error:

 File "03_pyfolio_demo.py", line 120, in <module>
    df = store.get('us_equities/stocks')['sector'].dropna()
  File "/opt/conda/envs/backtest/lib/python3.6/site-packages/pandas/io/pytables.py", line 670, in get
    raise KeyError('No object named %s in the file' % key)
KeyError: 'No object named us_equities/stocks in the file'

**Expected behavior**
n/a
**Screenshots**
n/a
**Environment**
python 3.6 
- OS: [Ubuntu]
 - Version [n/a]

**Additional context**
n/a

**Comment by JeremyWhittaker** [comment] 2021-04-30 17:11
Not sure if it helps but I couldn't get this to work when I built it out on Ubuntu. I ended up just using the Docker image. I know that's not a fix to your issue but it will get you to a point where you can move forward. I think there was recently a new version of Pyfolio released as well. I think he made a bunch of changes to the code in April. I'm not sure when you built out your environment but it may help to go back to the install instructions if it was awhile ago.

**Comment by stefan-jansen** [comment] 2021-04-30 17:18
You need to run the code under the section [Metadata on US-traded companies](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/data/create_datasets.ipynb) in the `create_datasets.ipynb` notebook in the `data` directory. 

Note the warning that the instructions at the beginning no longer work since NASDAQ changed it's website but I've included a file that has the data to reproduce the examples. This should solve the missing data issue.

**Closed by stefan-jansen** 2021-04-30 17:18 UTC
