### ISSUE TITLE
Chapter 05. positional indexers are out-of-bounds

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#78] opened 2020-12-17 20:29 UTC
I am practicing the file of the _pyfolio_demo.ipynb_.(first edition)

`returns, positions, transactions = extract_rets_pos_txn_from_zipline(backtest)`
`positions.columns = [c for c in positions.columns[:-1]] + ['cash']
positions.index = positions.index.normalize()
positions.info()`

`import pandas_datareader.data as web`    
`import datetime` 
`df = web.DataReader(name='SP500', data_source='fred', start=2009).squeeze().to_frame('close')` 
`with pd.HDFStore('C://Users//silen//Hands-On Machine Learning(1st Edition)//backtests.h5') as store:` 
`    store.put('sp500/fred', df)` 
`    benchmark_rets = store['sp500/fred'].close.pct_change()` 
`benchmark_rets.name = 'S&P500'` 
`benchmark_rets = benchmark_rets.tz_localize('UTC').filter(returns.index)` 

`plot_perf_stats(returns=returns, factor_returns=benchmark_rets)`

I got an error below

_IndexError: positional indexers are out-of-bounds_

how can I fix it?

**Comment by stefan-jansen** [comment] 2020-12-22 19:01
Could you please post the code and the full backtrace? It's not clear where the error occurs; it means that you are trying to access a position in an array (index) that does not exists, probably because there's fewer data than expected. You can properly format code using three backticks before and after, like so:

```
with pd.HDFStore('C://Users//silen//Hands-On Machine Learning(1st Edition)//backtests.h5') as store:
    store.put('sp500/fred', df)
```
That makes it easier to read.

**Comment by stefan-jansen** [comment] 2021-01-13 21:17
Closing for now absent further activity.

**Closed by stefan-jansen** 2021-01-13 21:17 UTC

**Comment by Francomv** [comment] 2024-10-25 13:38
The issue is that FRED sp500, in 2024, starts in 2014, while the returns of the exercise start at 2013. So, you should use the sp500 downloaded from Stooq and it will work. Example:

with pd.HDFStore(HDF_PATH) as store:
    benchmark_rets = store['sp500/**stooq**'].close.pct_change() #use stooq instead of FRED
benchmark_rets.name = 'S&P500'
benchmark_rets = benchmark_rets.tz_localize('UTC').filter(returns.index)
benchmark_rets.head()
