### ISSUE TITLE
Chapter 04 - 06_performance_eval_alphalens EOFError: Ran out of input

### ISSUE THREAD

**Issue by kmeans27** [stefan-jansen/machine-learning-for-trading#210] opened 2021-11-11 11:10 UTC
Hi, i finally got zipline runnning and created the single_factor.pickle file on the Chapter 04 - 04 single factor zipline Program.

but now i get a EOFERROR: Ran out of input when running the 06 Program:
EOFError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15276/2514104116.py in <module>
----> 1 performance = pd.read_pickle('single_factor.pickle')

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\pandas\io\pickle.py in read_pickle(filepath_or_buffer, compression, storage_options)
    201                     # We want to silence any warnings about, e.g. moved modules.
    202                     warnings.simplefilter("ignore", Warning)
--> 203                     return pickle.load(handles.handle)  # type: ignore[arg-type]
    204             except excs_to_catch:
    205                 # e.g.

EOFError: Ran out of input

![eoferror](https://user-images.githubusercontent.com/93648278/141288269-08091197-0f7f-4ee9-a2d9-e7aa0922793d.PNG)

Thank you so much! :-)

**Comment by yingh2013** [comment] 2021-11-27 19:29
I encountered similar issue.   
The problem is the file 'single_factor.pickle' is empty or bad.  'single_factor.pickle' is from output of prior chapter run:  04_single_factor_zipline.ipynb:
%%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle --no-benchmark --bundle quandl
Zipline-reloaded had issue to output pickle.    The latest version of zipline-reloaded 2.2  should resolve the issue.

**Comment by stefan-jansen** [comment] 2021-12-20 20:35
Closing for now - feel free to reopen if updating Zipline does not resolve this.

**Closed by stefan-jansen** 2021-12-20 20:35 UTC
