### ISSUE TITLE
chapter 02 _ 01 jupyter file , key error : No Object named P in the file .

### ISSUE THREAD

**Issue by mahdic200** [stefan-jansen/machine-learning-for-trading#328] opened 2024-09-17 00:25 UTC
**Describe the bug**
in the last cell , there is an error : No object found P in the file .

1. Go to chapter 2 in jupyter notebook 1
2. Click on run all cells
3. Scroll down to last cell
4. See error : no object named P in the file .

**Environment**
vscode jupyter notebook
 
- OS: ubuntu 24.04 LTS

**Comment by elsdes3** [comment] 2024-09-18 18:07
I think this is a duplicate of a [previously opened issue](https://github.com/stefan-jansen/machine-learning-for-trading/issues/310).

I recommend merging this issue with that one.

**Closed as completed** 2024-09-18 23:23 UTC
